language: node_js
node_js: "9.8.0"
install:
- npm install
before_script:
- npm run lint
script:
- npm run build
deploy:
  provider: s3
  region: eu-central-1
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $DOMAIN
  local_dir: dist
  cache_control: "max-age=21600"
  on:
    branch: dev
